### ISSUE TITLE
Data not working on G920W8

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [fakemanoan/LineageOS-Releases#27]
On my Galaxy S6 (SM-G920W8), mobile data does not work. I can turn it on but every app will say I have no internet. Calls and texts work fine.

Also -- Unsure if this is related, but on the lock screen, my carrier comes up wrong, on the top left corner of the lock screen where it shows my carrier name, it's supposed to say "VIRGIN", however it says "Bell", this doesn't worry me too much because Virgin Plus is an MVNO of Bell, but I figured it's worth mentioning just in case it's related. In the "Calls and SMS" and "SIMs" section in settings my carrier comes up as VIRGIN like it should.

**Comment by Lost-Entrepreneur439** [comment]
Update - It appears to be an LTE related problem. If I force it to use 3G, my data works fine.

**Comment by fakemanoan** [comment]
Hi
The Canadian models of S6 are currently unsupported and issues will arise as a result. This might change in the future, but for now I ask you to be patient and wait for official builds. Thanks :)

**Comment by Lost-Entrepreneur439** [comment]
> Hi The Canadian models of S6 are currently unsupported and issues will arise as a result. This might change in the future, but for now I ask you to be patient and wait for official builds. Thanks :)

I don't think there's ever going to be an official build for the W8. Due to how little Canadian ROM developers there are, and the fact that the S6 is apparently a really hard device to develop ROMs for, it makes the chances really low that there's going to be an official build for the W8.

**Comment by chunter2** [comment]
I've managed to come across three of these G920W8's from my parents and in-laws.  I'd be willing to help debug the data issue if you're still interested in working on it.  I tried out the first of the three test roms you posted in April of last year.  Just wondering what the difference is between the three just to save me downloading the other two.  

Thanks

**Comment by Lost-Entrepreneur439** [comment]
> I've managed to come across three of these G920W8's from my parents and in-laws. I'd be willing to help debug the data issue if you're still interested in working on it. I tried out the first of the three test roms you posted in April of last year. No luck with the data. Just wondering what the difference is between the three just to save me downloading the other two.
> 
> Thanks

It appears this issue has been somehow fixed in Android 13, I ported crDroid 9 to the S6 about a month ago, and I've had no issues on my G920W8. I haven't tested Lineage 20 however, so the issue may still be present there, I'm not sure.

**Comment by chunter2** [comment]
> It appears this issue has been somehow fixed in Android 13, I ported crDroid 9 to the S6 about a month ago, and I've had no issues on my G920W8. I haven't tested Lineage 20 however, so the issue may still be present there, I'm not sure.

I just tried your crDroidAndroid-13.0-20240209-zerofltexx-v9.13.zip file but still get the exclamation mark over the signal strength icon and no data.  Does it matter what carrier (Bell/Rogers) I'm using?  I'm using Fido (Rogers) on this SIM unlocked phone.

**Comment by chunter2** [comment]
@fakemanoan Any updates on this issue?

**Comment by fakemanoan** [comment]
Hi, there are no specific updates in relation to this issue. However I did swap to RIL blobs from a Note10 device, which fixes call audio and improves compatibility with later android versions. This might make a difference on W8 models, but hard to say for sure. 

That update is live on my lineage-19.1 builds and will be coming soon to my lineage-20 builds later today. Try that and see how it goes

**Comment by chunter2** [comment]
I tried your latest build on two of my G920W8's and the new RIL seems to work.  I have a data only plan so can't test voice or texts but the data seems to be good.  It does show 4G instead of LTE like the stock firmware did but that doesn't seem to matter.  

Thanks for the update.

**Comment by fakemanoan** [comment]
Cool. I will look to build for Canada models in the next release if all goes well in that time period.

**Comment by fakemanoan** [comment]
Hi all looking to try provide support for W8 models. Would any of you be willing to test 19.1 builds and provide feedback?

**Comment by fakemanoan** [comment]
I will attempt to upload some builds by the next ASB drop for Android 12.1 variants, just as a test

**Comment by fakemanoan** [comment]
Hi here is a test build. Would appreciate any feedback!
https://github.com/fakemanoan/lineage_ota/releases/download/untagged-3ac8fb7b08df9a9bf85f/lineage-19.1-20240513-UNOFFICIAL-zerofltecan.zip

**Comment by chunter2** [comment]
Sorry, missed these messages.  I'll see what I can do.  Does it matter what version of TWRP I'm using?  I think I've got your version installed.  Does it matter that yours isn't the can one?

**Comment by fakemanoan** [comment]
As long as you got 3.7.0-9.0 you are good to go. My TWRP builds are mainly for OTA stuff. 

Non-canadian TWRP shouldnt matter.

**Comment by chunter2** [comment]
I'm using TWRP_3.7.0-9.0_zeroflte_19012024.img but when I try to install your 19.1 image above I get this:
```
E3004: This package is for device: zerofltecan,zerofltebmc,zerofltetmo; this device is zeroflte.
Updater process ended with ERROR: 1
Error installing zip file '/sdcard/Download/lineage-19.1.20240513-UNOFFICIAL-zerofltecan.zip'

**Comment by fakemanoan** [comment]
sorry for the delay, try this
https://github.com/fakemanoan/lineage_ota/releases/download/can/lineage-19.1-20240513-UNOFFICIAL-zerofltecan-2.zip

**Comment by chunter2** [comment]
This one seems to work.  Data works as well even though it's still showing 4G instead of LTE.

**Comment by fakemanoan** [comment]
4G = LTE, just a visual change to bring it inline with stock appearance 
Let me know if you have any issues with calls, texts, etc

**Comment by chunter2** [comment]
Unfortunately I have a data only plan so I can't test calls and texts.  What's different with this builds RIL compared to your regular Lineage 20 zerofltexx builds RIL?

**Comment by fakemanoan** [comment]
This is using the RIL stack from Android 11 d2s. It fixes in call audio and removes a few legacy hacks, but at the cost of being able to use a SIM PIN unlock only on S6/S6 edge, works fine on the note 5 for some reason.

**Comment by chunter2** [comment]
Is that different than your Lineage 20 builds RIL?  Data worked for both roms for me.

**Comment by fakemanoan** [comment]
Same RIL is used on both los 20 and 19, but this build has specific changes for the audio earsmart ic present on these models.

**Comment by chunter2** [comment]
Oh, guess I'm not a good candidate to test the audio then.  Sorry.

**Comment by m4gicfour** [comment]
I may be able to test audio on this sometime around the end of this month

(My G920W8 is my backup phone, and my daily driver just died, hence my searching for a maintained rom for it; when the replacement for my daily driver arrives I should be able to test, barring any further problems.)

**Comment by fakemanoan** [comment]
As discussed in https://github.com/fakemanoan/LineageOS-Releases/issues/92, it appears that the build works properly with audio, and others here state the data problem is largely solved, SMS works etc. I will consider this ready to support. 

I might unify the devices, so I can just build once and it works on everything. Depends if there any more issues. I'll give it until I finish up the Android 11 updates I'm doing.

**Comment by m4gicfour** [comment]
> As discussed in #92, it appears that the build works properly with audio, and others here state the data problem is largely solved, SMS works etc. I will consider this ready to support.
> 
> I might unify the devices, so I can just build once and it works on everything. Depends if there any more issues. I'll give it until I finish up the Android 11 updates I'm doing.

In that case, I'll hold off flashing my G920W8 until you have an "official" build out, unless you need something specific tested in the meantime.

**Comment by fakemanoan** [comment]
Hey all, just pinging anyone in this thread or any new readers. If you could run the following command after taking a phone call  and upload it somewhere that would be appreciated:

``
adb logcat -b events -d
``

This is to address some potential SELinux denials for a potential future release with enforcing status.

**Comment by fakemanoan** [comment]
Bumping this again.

https://github.com/fakemanoan/LineageOS-Releases/issues/106

Here is a test 18.1 build with broad S6, S6 edge and Note 5 support. Provide logs when in a phone call so that I can write proper SELinux policies. Thanks!

**Comment by fakemanoan** [comment]
closing as this issue has long been resolved, and discussion can continue in the NA Exynos unified builds thread
